### ISSUE TITLE
please do not html escape post titles in your rss feed

### ISSUE THREAD

**Issue by a4z** [Philip-Trettner/Philip-Trettner.github.io#1]
Hi Philip, 
I added your blog to the list of C++ relevant blogs I have here 
https://www.swedencpp.se/blogs
Thanks a lot for your interesting posts! 

Just one thing:
The title of your blog is shown, for example as `always_false&lt;T&gt;` , even if it should be `always_false<T>` 

I guess the reason is that you have the html escaped text in your rss feed, but this text should be human readable, not html readable. At least, I do not have this kind of problem with any other feed I process, so I guess this is the reason. (Web tech is not may domain;-) ) 
You might want to consider changing that ?

**Comment by Philip-Trettner** [comment]
Thanks for bringing that to my attention!
I did that because otherwise Jekyll would not display it correctly on the starting page.
Let me see if I can fix that somehow.

**Comment by Philip-Trettner** [comment]
Hm I'm not sure if I fixed the problem properly. So now I can at least use `<T>` in a title without jekyll swallowing it on the blog. But I think the rss feed stripped it now. Well at least it's an improvement because it's not html escaped anymore?

**Comment by a4z** [comment]
I can see there was some change, now the title is `always_false`  , so the `<T>` went away
you can check your feed, https://artificial-mind.net/feed.xml 

look at the title tag 
`<title type="html">always_false</title>` 
not sure what the `type="html"`makes there , never seen this in an other rss or atom feed

I think your atom.xml template looks corrects, it does not include that attrib, but maybe that is not used but some other template?

**Comment by Philip-Trettner** [comment]
Ok so the feed xml template I had in that template wasn't included at all. I also didn't manage to make that one work so I switched to an atom-based feed. The URL stays the same but it is now a different format.

The title on your page is correct now, did you edit that manually or is it generated?

**Comment by a4z** [comment]
The page is generated, so it refreshes itself every now and then.
I did not have to do anything, so obviously your fix did the right thing.
Awesome, thanks!
